### ISSUE TITLE
cursor goes to next line after inputting symbol

### ISSUE THREAD

**Issue by amybruno** [joom/latex-unicoder.vim#10]
Whenever I use latex-unicoder to input a symbol, the cursor always ends up moving to the next line after the symbol gets inputted. Which is to say that this happens:
1. I press C-l
2. I type something, e.g. `\lambda`
3. I press <Enter>
4. λ gets inserted at the cursor
5. The cursor moves down to the first character of the next line.

The desired behaviour would of  course be that the cursor just moves so that it's immediately after the symbol.

**Comment by yglunl** [comment]
```
diff --git a/autoload/unicoder.vim b/autoload/unicoder.vim
index 58d4846..bc2410b 100644
--- a/autoload/unicoder.vim
+++ b/autoload/unicoder.vim
@@ -2534,7 +2534,7 @@ function! unicoder#start(insert)
   execute 'normal! ' . how . s
 
   if a:insert > 0
-    startinsert!
+    startinsert
     normal! l
   endif
 endfunction

```
This should fix it, but doesn't work if inserting at the end of the line.

**Comment by shuber2** [comment]
@amybruno Is this issue fixed? If yes then you may close this issue.
