### ISSUE TITLE
Is there a way to avoid key bindings? 

### ISSUE THREAD

**Issue by mmngreco** [joom/latex-unicoder.vim#20]
When I add `latex-unicoder` to my `init.vim` I lost my desired behaviour for `<C-l>` shortcut. is there a way to avoid this? 

I try adding:

```
" ========= latex unicoder ==========
let g:unicoder_cancel_normal = 1
let g:unicoder_cancel_insert = 1
let g:unicoder_cancel_visual = 1
nnoremap <F3> :call unicoder#start(0)<CR>
inoremap <F3> <Esc>:call unicoder#start(1)<CR>
vnoremap <F3> :<C-u>call unicoder#selection()<CR>
```

but not takes effect.

**Comment by martinsifrar** [comment]
Take a look at #8. The fix by @rperce was merged in #9 and currently works for me.

**Comment by mmngreco** [comment]
Nice, that's exactly what I'm looking for. I should have seen that issue before. Thanks!

**Comment by shuber2** [comment]
@mmngreco You could close this issue, I guess.
